<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Param;

class ParamsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('params')->truncate();
        DB::table('param_values')->truncate();
        $dataParams = [
            [
                'name' => 'Hair Color',
                'type' => Param::TYPE_ONE,
                'is_profile' => true,
                'is_matches' => true,
                'type_match' => Param::TYPE_MANY,
                'is_search' => true,
                'type_search' => Param::TYPE_MANY,
                'values' => [
                    ['name' => 'Bald / Shaved',],
                    ['name' => 'Black',],
                    ['name' => 'Blonde',],
                    ['name' => 'Brown',],
                    ['name' => 'Grey / White',],
                    ['name' => 'Light Brown',],
                    ['name' => 'Red',],
                    ['name' => 'Changes frequently',],
                ]
            ],
            [
                'name' => 'Hair length',
                'type' => Param::TYPE_ONE,
                'is_profile' => true,
                'is_search' => true,
                'is_matches' => true,
                'type_match' => Param::TYPE_MANY,
                'type_search' => Param::TYPE_MANY,
                'values' => [
                    ['name' => 'Bald',],
                    ['name' => 'Bald on Top',],
                    ['name' => 'Shaved',],
                    ['name' => 'Short',],
                    ['name' => 'Medium',],
                    ['name' => 'Long',],
                    ['name' => 'Prefer not to say',],
                ]
            ],
            [
                'name' => 'Eye color',
                'type' => Param::TYPE_ONE,
                'is_search' => true,
                'is_profile' => true,
                'is_matches' => true,
                'type_match' => Param::TYPE_MANY,
                'type_search' => Param::TYPE_MANY,
                'values' => [
                    ['name' => 'Black',],
                    ['name' => 'Blue',],
                    ['name' => 'Brown',],
                    ['name' => 'Green',],
                    ['name' => 'Grey',],
                    ['name' => 'Hazel',],
                ]
            ],

            [
                'name' => 'Eye wear',
                'type' => Param::TYPE_ONE,
                'is_profile' => true,
                'is_search' => true,
                'is_matches' => true,
                'type_match' => Param::TYPE_MANY,
                'type_search' => Param::TYPE_MANY,
                'values' => [
                    ['name' => 'Contacts',],
                    ['name' => 'Glasses',],
                    ['name' => 'None',],
                    ['name' => 'Prefer not to say',],
                ]
            ],
            [
                'name' => 'Height',
                'type' => Param::TYPE_FIXED,
                'is_profile' => true,
            ],
            [
                'name' => 'Weight',
                'type' => Param::TYPE_FIXED,
                'is_profile' => true,
                'is_search' => true,
                'type_search' => Param::TYPE_MANY,
            ],
            [
                'name' => 'Body type',
                'type' => Param::TYPE_ONE,
                'is_profile' => true,
                'is_matches' => true,
                'type_match' => Param::TYPE_MANY,
                'is_search' => true,
                'type_search' => Param::TYPE_MANY,
                'values' => [
                    ['name' => 'Petite',],
                    ['name' => 'Slim',],
                    ['name' => 'Athletic',],
                    ['name' => 'Average',],
                    ['name' => 'Few Extra Pounds',],
                    ['name' => 'Full Figured',],
                    ['name' => 'Large and Lovely',],
                ]
            ],
            [
                'name' => 'Your ethnicity is mostly',
                'type' => Param::TYPE_ONE,
                'is_profile' => true,
                'is_matches' => true,
                'type_match' => Param::TYPE_MANY,
                'is_search' => true,
                'type_search' => Param::TYPE_MANY,
                'values' => [
                    ['name' => 'Arab (Middle Eastern)',],
                    ['name' => 'Asian',],
                    ['name' => 'Black',],
                    ['name' => 'Caucasian (White)',],
                    ['name' => 'Hispanic / Latino',],
                    ['name' => 'Indian',],
                    ['name' => 'Mixed',],
                    ['name' => 'Pacific Islander',],
                    ['name' => 'Other',],
                ]
            ],
            [
                'name' => 'I consider my appearance as:',
                'type' => Param::TYPE_ONE,
                'is_profile' => true,
                'is_matches' => true,
                'type_match' => Param::TYPE_MANY,
                'is_search' => true,
                'type_search' => Param::TYPE_MANY,
                'values' => [
                    ['name' => 'Below average',],
                    ['name' => 'Average',],
                    ['name' => 'Attractive',],
                    ['name' => 'Very attractive',],
                ]
            ],
            [
                'name' => 'Do you drink?',
                'type' => Param::TYPE_ONE,
                'is_profile' => true,
                'is_matches' => true,
                'type_match' => Param::TYPE_MANY,
                'is_search' => true,
                'type_search' => Param::TYPE_MANY,
                'values' => [
                    ['name' => 'Do drink',],
                    ['name' => 'Don\'t drink',],
                    ['name' => 'Occasionally drink',],
                ]
            ],
            [
                'name' => 'Do you smoke?',
                'type' => Param::TYPE_ONE,
                'is_profile' => true,
                'is_matches' => true,
                'type_match' => Param::TYPE_MANY,
                'is_search' => true,
                'type_search' => Param::TYPE_MANY,
                'values' => [
                    ['name' => 'Do smoke',],
                    ['name' => 'Don\'t smoke',],
                    ['name' => 'Occasionally smoke',],
                ]
            ],
            [
                'name' => 'Marital Status:',
                'type' => Param::TYPE_ONE,
                'is_profile' => true,
                'is_matches' => true,
                'type_match' => Param::TYPE_MANY,
                'is_search' => true,
                'type_search' => Param::TYPE_MANY,
                'values' => [
                    ['name' => 'Single',],
                    ['name' => 'Separated',],
                    ['name' => 'Widowed',],
                    ['name' => 'Divorced',],
                    ['name' => 'Other',],
                ]
            ],
            [
                'name' => 'Do you have children?',
                'type' => Param::TYPE_ONE,
                'is_profile' => true,
                'is_matches' => true,
                'type_match' => Param::TYPE_MANY,
                'is_search' => true,
                'type_search' => Param::TYPE_MANY,
                'values' => [
                    ['name' => 'No',],
                    ['name' => 'Yes - don\'t live at home',],
                    ['name' => 'Yes - sometimes live at home',],
                    ['name' => 'Yes - live at home',],
                ]
            ],
            [
                'name' => 'Number of children:',
                'type' => Param::TYPE_FIXED,
                'is_profile' => true,
            ],
            [
                'name' => 'Oldest child:',
                'type' => Param::TYPE_FIXED,
                'is_profile' => true,
                'is_search' => true,
                'is_matches' => true,
                'type_match' => Param::TYPE_FIXED,
                'type_search' => Param::TYPE_FIXED,
            ],
            [
                'name' => 'Youngest child:',
                'type' => Param::TYPE_FIXED,
                'is_profile' => true,
                'is_search' => true,
                'is_matches' => true,
                'type_match' => Param::TYPE_FIXED,
                'type_search' => Param::TYPE_FIXED,
            ],
            [
                'name' => 'Do you want (more) children?',
                'type' => Param::TYPE_ONE,
                'is_profile' => true,
                'is_search' => true,
                'is_matches' => true,
                'type_search' => Param::TYPE_MANY,
                'type_match' => Param::TYPE_MANY,
                'values' => [
                    ['name' => 'Yes',],
                    ['name' => 'Not Sure',],
                    ['name' => 'No',],
                ]
            ],
            [
                'name' => 'Do you have pets?',
                'type' => Param::TYPE_MANY,
                'is_profile' => true,
                'values' => [
                    ['name' => 'Bird',],
                    ['name' => 'Cat',],
                    ['name' => 'Dog',],
                    ['name' => 'Exotic pets',],
                    ['name' => 'Fish',],
                    ['name' => 'Hamster / Guinea Pigs',],
                    ['name' => 'Horse',],
                    ['name' => 'Rabbit',],
                    ['name' => 'Reptile',],
                    ['name' => 'Other',],
                    ['name' => 'No Pets',],
                    ['name' => 'Prefer not to say',],
                ]
            ],
            [
                'name' => 'Occupation',
                'type' => Param::TYPE_ONE,
                'is_profile' => true,
                'values' => [
                    ['name' => 'Administrative / Secretarial / Clerical',],
                    ['name' => 'Advertising / Media',],
                    ['name' => 'Artistic / Creative / Performance',],
                    ['name' => 'Construction / Trades',],
                    ['name' => 'Domestic Helper',],
                    ['name' => 'Education / Academic',],
                    ['name' => 'Entertainment / Media',],
                    ['name' => 'Executive / Management / HR',],
                    ['name' => 'Farming / Agriculture',],
                    ['name' => 'Finance / Banking / Real Estate',],
                    ['name' => 'Fire / law enforcement / security',],
                    ['name' => 'Hair Dresser / Personal Grooming',],
                    ['name' => 'IT / Communications',],
                    ['name' => 'Laborer / Manufacturing',],
                    ['name' => 'Legal',],
                    ['name' => 'Medical / Dental / Veterinary',],
                    ['name' => 'Military',],
                    ['name' => 'Nanny / Child care',],
                    ['name' => 'No occupation / Stay at home',],
                    ['name' => 'Non-profit / clergy / social services',],
                    ['name' => 'Political / Govt / Civil Service',],
                    ['name' => 'Retail / Food services',],
                    ['name' => 'Retired',],
                    ['name' => 'Sales / Marketing',],
                    ['name' => 'Self Employed',],
                    ['name' => 'Student',],
                    ['name' => 'Technical / Science / Engineering',],
                    ['name' => 'Transportation',],
                    ['name' => 'Travel / Hospitality',],
                    ['name' => 'Unemployed',],
                    ['name' => 'Other',],
                ]
            ],
            [
                'name' => 'Employment status',
                'type' => Param::TYPE_ONE,
                'is_profile' => true,
                'is_search' => true,
                'is_matches' => true,
                'type_match' => Param::TYPE_MANY,
                'type_search' => Param::TYPE_MANY,
                'values' => [
                    ['name' => 'Student',],
                    ['name' => 'Part Time',],
                    ['name' => 'Full Time',],
                    ['name' => 'Homemaker',],
                    ['name' => 'Retired',],
                    ['name' => 'Not Employed',],
                    ['name' => 'Other',],
                    ['name' => 'Prefer not to say',],
                ]
            ],
            [
                'name' => 'Home type',
                'type' => Param::TYPE_ONE,
                'is_profile' => true,
                'is_search' => true,
                'is_matches' => true,
                'type_match' => Param::TYPE_MANY,
                'type_search' => Param::TYPE_MANY,
                'values' => [
                    ['name' => 'Apartment / Flat',],
                    ['name' => 'Condominium',],
                    ['name' => 'Farm',],
                    ['name' => 'House',],
                    ['name' => 'Town house',],
                    ['name' => 'Other',],
                    ['name' => 'Prefer not to say',],
                ]
            ],
            [
                'name' => 'Living situation',
                'type' => Param::TYPE_ONE,
                'is_profile' => true,
                'is_search' => true,
                'is_matches' => true,
                'type_match' => Param::TYPE_MANY,
                'type_search' => Param::TYPE_MANY,
                'values' => [
                    ['name' => 'Live Alone',],
                    ['name' => 'Live with friends',],
                    ['name' => 'Live with family',],
                    ['name' => 'Live with kids',],
                    ['name' => 'Live with spouse',],
                    ['name' => 'Other',],
                    ['name' => 'Prefer not to say',],
                ]
            ],
            [
                'name' => 'Willing to relocate',
                'type' => Param::TYPE_ONE,
                'is_profile' => true,
                'is_matches' => true,
                'type_match' => Param::TYPE_MANY,
                'is_search' => true,
                'type_search' => Param::TYPE_MANY,
                'values' => [
                    ['name' => 'Willing to relocate within my country',],
                    ['name' => 'Willing to relocate to another country',],
                    ['name' => 'Not willing to relocate',],
                    ['name' => 'Not sure about relocating',],
                ]
            ],
            [
                'name' => 'Relationship you\'re looking for',
                'type' => Param::TYPE_MANY,
                'is_profile' => true,
                'type_match' => Param::TYPE_MANY,
                'is_search' => true,
                'values' => [
                    ['name' => 'Penpal',],
                    ['name' => 'Friendship',],
                    ['name' => 'Romance / Dating',],
                    ['name' => 'Long Term Relationship',],
                    ['name' => 'Any',],
                ]
            ],
            [
                'name' => 'Nationality',
                'type' => Param::TYPE_ONE,
                'is_profile' => true,
                'is_matches' => true,
                'is_search' => true,
                'type_match' => Param::TYPE_MANY,
                'type_search' => Param::TYPE_MANY,
                'values' => [
                    ['name' => 'Philippines ',],
                    ['name' => 'United States',],
                    ['name' => 'Afghanistan ',],
                    ['name' => 'Albania ',],
                    ['name' => 'Algeria ',],
                    ['name' => 'American Samoa  ',],
                    ['name' => 'Andorra ',],
                    ['name' => 'Angola  ',],
                    ['name' => 'Anguilla',],
                    ['name' => 'Antarctica  ',],
                    ['name' => 'Antigua and Barbuda ',],
                    ['name' => 'Argentina   ',],
                    ['name' => 'Armenia ',],
                    ['name' => 'Aruba   ',],
                    ['name' => 'Australia   ',],
                    ['name' => 'Austria ',],
                    ['name' => 'Azerbaijan  ',],
                    ['name' => 'Bahamas ',],
                    ['name' => 'Bahrain ',],
                    ['name' => 'Bangladesh  ',],
                    ['name' => 'Barbados',],
                    ['name' => 'Belarus ',],
                    ['name' => 'Belgium ',],
                    ['name' => 'Belize  ',],
                    ['name' => 'Benin   ',],
                    ['name' => 'Bermuda ',],
                    ['name' => 'Bhutan  ',],
                    ['name' => 'Bolivia ',],
                    ['name' => 'Bonaire, St Eustatius, Saba ',],
                    ['name' => 'Bosnia &amp; Herzegovina',],
                    ['name' => 'Botswana',],
                    ['name' => 'Bouvet Island   ',],
                    ['name' => 'Brazil  ',],
                    ['name' => 'British Indian Ocean',],
                    ['name' => 'Brunei  ',],
                    ['name' => 'Bulgaria',],
                    ['name' => 'Burkina Faso',],
                    ['name' => 'Burundi ',],
                    ['name' => 'Cambodia',],
                    ['name' => 'Cameroon',],
                    ['name' => 'Canada  ',],
                    ['name' => 'Cape Verde  ',],
                    ['name' => 'Cayman Islands  ',],
                    ['name' => 'Central African Rep.',],
                    ['name' => 'Chad',],
                    ['name' => 'Chile',],
                    ['name' => 'China',],
                    ['name' => 'Christmas Island',],
                    ['name' => 'Cocos (Keeling) Is. ',],
                    ['name' => 'Colombia',],
                    ['name' => 'Comoros ',],
                    ['name' => 'Congo, Dem. Rep ',],
                    ['name' => 'Congo, Republic ',],
                    ['name' => 'Cook Islands',],
                    ['name' => 'Costa Rica',],
                    ['name' => 'Cote d\'Ivoire',],
                    ['name' => 'Croatia ',],
                    ['name' => 'Cuba',],
                    ['name' => 'Cyprus  ',],
                    ['name' => 'Czechia ',],
                    ['name' => 'Denmark ',],
                    ['name' => 'Djibouti',],
                    ['name' => 'Dominica',],
                    ['name' => 'Dominican Republic  ',],
                    ['name' => 'Ecuador ',],
                    ['name' => 'Egypt',],
                    ['name' => 'El Salvador ',],
                    ['name' => 'Equatorial Guinea   ',],
                    ['name' => 'Eritrea ',],
                    ['name' => 'Estonia ',],
                    ['name' => 'Eswatini',],
                    ['name' => 'Ethiopia',],
                    ['name' => 'Falkland Islands',],
                    ['name' => 'Faroe Islands   ',],
                    ['name' => 'Fiji',],
                    ['name' => 'Finland ',],
                    ['name' => 'France  ',],
                    ['name' => 'French Antarctic',],
                    ['name' => 'French Guiana',],
                    ['name' => 'French Polynesia',],
                    ['name' => 'Gabon',],
                    ['name' => 'Gambia  ',],
                    ['name' => 'Georgia ',],
                    ['name' => 'Germany ',],
                    ['name' => 'Ghana',],
                    ['name' => 'Gibraltar',],
                    ['name' => 'Greece  ',],
                    ['name' => 'Greenland',],
                    ['name' => 'Grenada ',],
                    ['name' => 'Guadeloupe  ',],
                    ['name' => 'Guam',],
                    ['name' => 'Guatemala',],
                    ['name' => 'Guernsey',],
                    ['name' => 'Guinea  ',],
                    ['name' => 'Guinea-Bissau',],
                    ['name' => 'Guyana  ',],
                    ['name' => 'Haiti',],
                    ['name' => 'Heard &amp; McDonald Is ',],
                    ['name' => 'Holy See (Vatican City) ',],
                    ['name' => 'Honduras',],
                    ['name' => 'Hong Kong (China)',],
                    ['name' => 'Hungary ',],
                    ['name' => 'Iceland ',],
                    ['name' => 'India',],
                    ['name' => 'Indonesia',],
                    ['name' => 'Iran',],
                    ['name' => 'Iraq',],
                    ['name' => 'Ireland ',],
                    ['name' => 'Isle of Man ',],
                    ['name' => 'Israel  ',],
                    ['name' => 'Italy',],
                    ['name' => 'Jamaica ',],
                    ['name' => 'Japan',],
                    ['name' => 'Jersey  ',],
                    ['name' => 'Jordan  ',],
                    ['name' => 'Kazakhstan  ',],
                    ['name' => 'Kenya',],
                    ['name' => 'Kiribati',],
                    ['name' => 'Korea, North',],
                    ['name' => 'Korea, South',],
                    ['name' => 'Kuwait  ',],
                    ['name' => 'Kyrgyzstan  ',],
                    ['name' => 'Laos',],
                    ['name' => 'Latvia  ',],
                    ['name' => 'Lebanon ',],
                    ['name' => 'Lesotho ',],
                    ['name' => 'Liberia ',],
                    ['name' => 'Libya',],
                    ['name' => 'Liechtenstein',],
                    ['name' => 'Lithuania',],
                    ['name' => 'Luxembourg  ',],
                    ['name' => 'Macau (China)',],
                    ['name' => 'Macedonia (FYR) ',],
                    ['name' => 'Madagascar  ',],
                    ['name' => 'Malawi  ',],
                    ['name' => 'Malaysia',],
                    ['name' => 'Maldives',],
                    ['name' => 'Mali',],
                    ['name' => 'Malta',],
                    ['name' => 'Marshall Islands',],
                    ['name' => 'Martinique  ',],
                    ['name' => 'Mauritania  ',],
                    ['name' => 'Mauritius',],
                    ['name' => 'Mayotte ',],
                    ['name' => 'Mexico  ',],
                    ['name' => 'Micronesia  ',],
                    ['name' => 'Moldova ',],
                    ['name' => 'Monaco  ',],
                    ['name' => 'Mongolia',],
                    ['name' => 'Montserrat  ',],
                    ['name' => 'Morocco ',],
                    ['name' => 'Mozambique  ',],
                    ['name' => 'Myanmar ',],
                    ['name' => 'Namibia ',],
                    ['name' => 'Nauru',],
                    ['name' => 'Nepal',],
                    ['name' => 'Netherlands ',],
                    ['name' => 'New Caledonia',],
                    ['name' => 'New Zealand ',],
                    ['name' => 'Nicaragua',],
                    ['name' => 'Niger',],
                    ['name' => 'Nigeria ',],
                    ['name' => 'Niue',],
                    ['name' => 'Norfolk Island  ',],
                    ['name' => 'Northern Mariana Is.',],
                    ['name' => 'Norway  ',],
                    ['name' => 'Oman',],
                    ['name' => 'Pakistan',],
                    ['name' => 'Palau',],
                    ['name' => 'Palestine',],
                    ['name' => 'Panama',],
                    ['name' => 'Papua New Guinea',],
                    ['name' => 'Paraguay',],
                    ['name' => 'Peru',],
                    ['name' => 'Pitcairn Islands',],
                    ['name' => 'Poland  ',],
                    ['name' => 'Portugal',],
                    ['name' => 'Puerto Rico ',],
                    ['name' => 'Qatar',],
                    ['name' => 'Reunion ',],
                    ['name' => 'Romania ',],
                    ['name' => 'Russia',],
                    ['name' => 'Rwanda',],
                    ['name' => 'Saint Helena',],
                    ['name' => 'Saint Lucia ',],
                    ['name' => 'Samoa',],
                    ['name' => 'San Marino  ',],
                    ['name' => 'Sao Tome &amp; Principe ',],
                    ['name' => 'Saudi Arabia',],
                    ['name' => 'Senegal ',],
                    ['name' => 'Serbia  ',],
                    ['name' => 'Seychelles  ',],
                    ['name' => 'Sierra Leone',],
                    ['name' => 'Singapore',],
                    ['name' => 'Slovakia',],
                    ['name' => 'Slovenia',],
                    ['name' => 'Solomon Islands ',],
                    ['name' => 'Somalia ',],
                    ['name' => 'South Africa',],
                    ['name' => 'South Georgia Island',],
                    ['name' => 'Spain',],
                    ['name' => 'Sri Lanka',],
                    ['name' => 'St Kitts &amp; Nevis',],
                    ['name' => 'St Pierre &amp;  Miquelon',],
                    ['name' => 'St Vincent Grenadines',],
                    ['name' => 'Sudan',],
                    ['name' => 'Suriname',],
                    ['name' => 'Svalbard &amp; Jan Mayen',],
                    ['name' => 'Sweden  ',],
                    ['name' => 'Switzerland ',],
                    ['name' => 'Syria',],
                    ['name' => 'Taiwan (China)  ',],
                    ['name' => 'Tajikistan  ',],
                    ['name' => 'Tanzania',],
                    ['name' => 'Thailand',],
                    ['name' => 'Timor Leste ',],
                    ['name' => 'Togo',],
                    ['name' => 'Tokelau ',],
                    ['name' => 'Tonga',],
                    ['name' => 'Trinidad and Tobago ',],
                    ['name' => 'Tunisia ',],
                    ['name' => 'Turkey  ',],
                    ['name' => 'Turkmenistan',],
                    ['name' => 'Turks &amp; Caicos Is.  ',],
                    ['name' => 'Tuvalu  ',],
                    ['name' => 'Uganda  ',],
                    ['name' => 'Ukraine ',],
                    ['name' => 'United Arab Emirates',],
                    ['name' => 'United Kingdom  ',],
                    ['name' => 'Uruguay ',],
                    ['name' => 'US Minor Outlying Is',],
                    ['name' => 'Uzbekistan  ',],
                    ['name' => 'Vanuatu ',],
                    ['name' => 'Venezuela',],
                    ['name' => 'Vietnam ',],
                    ['name' => 'Virgin Islands (British)',],
                    ['name' => 'Virgin Islands (US) ',],
                    ['name' => 'Wallis and Futuna   ',],
                    ['name' => 'Western Sahara  ',],
                    ['name' => 'Yemen ',],
                    ['name' => 'Zambia  ',],
                    ['name' => 'Zimbabwe',],
                ]
            ],
            [
                'name' => 'Education',
                'type' => Param::TYPE_ONE,
                'is_profile' => true,
                'is_matches' => true,
                'type_match' => Param::TYPE_MANY,
                'is_search' => true,
                'type_search' => Param::TYPE_MANY,
                'values' => [
                    ['name' => 'Primary (Elementary) School',],
                    ['name' => 'Middle School / Junior High',],
                    ['name' => 'High School',],
                    ['name' => 'Vocational College',],
                    ['name' => 'Bachelors Degree',],
                    ['name' => 'Masters Degree',],
                    ['name' => 'PhD or Doctorate',],
                ]
            ],
            [
                'name' => 'Languages spoken',
                'type' => Param::TYPE_MANY,
                'is_profile' => true,
                'is_matches' => true,
                'type_match' => Param::TYPE_MANY,
                'is_search' => true,
                'type_search' => Param::TYPE_MANY,
                'values' => [
                    ['name' => 'Arabic',],
                    ['name' => 'Dutch',],
                    ['name' => 'English',],
                    ['name' => 'French',],
                    ['name' => 'German',],
                    ['name' => 'Italian',],
                    ['name' => 'Japanese',],
                    ['name' => 'Spanish',],
                    ['name' => 'Tagalog',],
                    ['name' => 'Cebuano',],
                    ['name' => 'Armenian',],
                    ['name' => 'Afrikaans',],
                    ['name' => 'Albanian',],
                    ['name' => 'Amharic',],
                    ['name' => 'Assyrian',],
                    ['name' => 'Azerbaijani',],
                    ['name' => 'Bahasa Malay / Indonesian',],
                    ['name' => 'Belorussian',],
                    ['name' => 'Bengali',],
                    ['name' => 'Berber',],
                    ['name' => 'Bulgarian',],
                    ['name' => 'Burmese',],
                    ['name' => 'Chinese (Cantonese)',],
                    ['name' => 'Chinese (Mandarin)',],
                    ['name' => 'Creole',],
                    ['name' => 'Croatian',],
                    ['name' => 'Czech',],
                    ['name' => 'Danish',],
                    ['name' => 'Eritrean',],
                    ['name' => 'Estonian',],
                    ['name' => 'Farsi',],
                    ['name' => 'Finnish',],
                    ['name' => 'Georgian',],
                    ['name' => 'Greek',],
                    ['name' => 'Gujarati',],
                    ['name' => 'Hausa',],
                    ['name' => 'Hebrew',],
                    ['name' => 'Hindi',],
                    ['name' => 'Hungarian',],
                    ['name' => 'Icelandic',],
                    ['name' => 'Iilocano',],
                    ['name' => 'Inuktitut',],
                    ['name' => 'Kazakh',],
                    ['name' => 'Khmer',],
                    ['name' => 'Kirgiz',],
                    ['name' => 'Korean',],
                    ['name' => 'Kurdish',],
                    ['name' => 'Kutchi',],
                    ['name' => 'Kyrgiz',],
                    ['name' => 'Laotian',],
                    ['name' => 'Latvian',],
                    ['name' => 'Lithuanian ',],
                    ['name' => 'Macedonian ',],
                    ['name' => 'Malagasy',],
                    ['name' => 'Malayalam',],
                    ['name' => 'Maldivian',],
                    ['name' => 'Maltese',],
                    ['name' => 'Marathi',],
                    ['name' => 'Mongolian',],
                    ['name' => 'Nepali',],
                    ['name' => 'Norwegian',],
                    ['name' => 'Pashto',],
                    ['name' => 'Persian',],
                    ['name' => 'Pidgin',],
                    ['name' => 'Polish',],
                    ['name' => 'Portuguese ',],
                    ['name' => 'Quechua',],
                    ['name' => 'Romanian',],
                    ['name' => 'Russian',],
                    ['name' => 'Serbian',],
                    ['name' => 'Sindhi',],
                    ['name' => 'Sinhala',],
                    ['name' => 'Slovak',],
                    ['name' => 'Slovene',],
                    ['name' => 'Somali',],
                    ['name' => 'Swahili',],
                    ['name' => 'Swedish',],
                    ['name' => 'Tamil',],
                    ['name' => 'Telugu',],
                    ['name' => 'Thai ',],
                    ['name' => 'Tibetan',],
                    ['name' => 'Tongan',],
                    ['name' => 'Turkish',],
                    ['name' => 'Turkmen',],
                    ['name' => 'Ugaritic',],
                    ['name' => 'Ukrainian',],
                    ['name' => 'Urdu',],
                    ['name' => 'Uzbek',],
                    ['name' => 'Vietnamese',],
                    ['name' => 'Welsh',],
                    ['name' => 'Other',],
                ]
            ],
            [
                'name' => 'English language ability',
                'type' => Param::TYPE_ONE,
                'is_profile' => true,
                'is_matches' => true,
                'type_match' => Param::TYPE_MANY,
                'is_search' => true,
                'type_search' => Param::TYPE_MANY,
                'values' => [
                    ['name' => 'None',],
                    ['name' => 'Some',],
                    ['name' => 'Good',],
                    ['name' => 'Very Good',],
                    ['name' => 'Fluent',],
                ]
            ],
            [
                'name' => 'Religion',
                'type' => Param::TYPE_ONE,
                'is_profile' => true,
                'is_matches' => true,
                'type_match' => Param::TYPE_MANY,
                'is_search' => true,
                'type_search' => Param::TYPE_MANY,
                'values' => [
                    ['name' => 'Bahá\'í',],
                    ['name' => 'Buddhist',],
                    ['name' => 'Christian - Catholic',],
                    ['name' => 'Christian - Other',],
                    ['name' => 'Christian - Protestant',],
                    ['name' => 'Hindu',],
                    ['name' => 'Islam',],
                    ['name' => 'Jainism',],
                    ['name' => 'Jewish',],
                    ['name' => 'Parsi',],
                    ['name' => 'Shintoism',],
                    ['name' => 'Sikhism',],
                    ['name' => 'Taoism',],
                    ['name' => 'Other',],
                    ['name' => 'No religion',],
                ]
            ],
            [
                'name' => 'Star sign',
                'type' => Param::TYPE_ONE,
                'is_profile' => true,
                'is_search' => true,
                'type_search' => Param::TYPE_MANY,
                'is_matches' => true,
                'type_match' => Param::TYPE_MANY,
                'values' => [
                    ['name' => 'Aquarius',],
                    ['name' => 'Aries',],
                    ['name' => 'Cancer',],
                    ['name' => 'Capricorn',],
                    ['name' => 'Gemini',],
                    ['name' => 'Leo',],
                    ['name' => 'Libra',],
                    ['name' => 'Pisces',],
                    ['name' => 'Sagittarius',],
                    ['name' => 'Scorpio',],
                    ['name' => 'Taurus',],
                    ['name' => 'Virgo',],
                    ['name' => 'Don\'t Know',],
                ]
            ],
            [
                'name' => 'Height from',
                'is_profile' => false,
                'is_matches' => true,
                'type_match' => Param::TYPE_FIXED,
                'is_search' => true,
                'type_search' => Param::TYPE_FIXED,
            ],
            [
                'name' => 'Height to',
                'is_profile' => false,
                'is_matches' => true,
                'type_match' => Param::TYPE_FIXED,
                'is_search' => true,
                'type_search' => Param::TYPE_FIXED,
            ],
            [
                'name' => 'Weight from',
                'is_profile' => false,
                'is_matches' => true,
                'type_match' => Param::TYPE_FIXED,
                'is_search' => true,
                'type_search' => Param::TYPE_FIXED,
            ],
            [
                'name' => 'Weight to',
                'is_profile' => false,
                'is_matches' => true,
                'type_match' => Param::TYPE_FIXED,
                'is_search' => true,
                'type_search' => Param::TYPE_FIXED,
            ],
        ];

        foreach($dataParams as $data) {
            $dataParam = array_except($data, ['values']);
            $dataParam['alias'] = str_slug($dataParam['name'],'_');
            $param = Param::create($dataParam);
            if(in_array($param->type, [Param::TYPE_ONE, Param::TYPE_MANY])) {
                foreach($data['values'] as $dataValue) {
                    $param->values()->create($dataValue);
                }
            }
        }
    }
}
